# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-03 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherName', models.CharField(max_length=20)),
                ('publishTime', models.CharField(max_length=40)),
                ('issuer', models.CharField(max_length=20)),
                ('intruction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameReviewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewInfo', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GameSum',
            fields=[
                ('gameId', models.AutoField(primary_key=True, serialize=False)),
                ('gameName', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=200)),
                ('image', models.CharField(default='/Static/image/Game/404.jpg', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('passWord', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(default=0)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameReviewApp.GameSum')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameReviewApp.Register')),
            ],
        ),
        migrations.AddField(
            model_name='gamereviewinfo',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameReviewApp.GameSum'),
        ),
        migrations.AddField(
            model_name='gamereviewinfo',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameReviewApp.Register'),
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameReviewApp.GameSum'),
        ),
        migrations.AlterUniqueTogether(
            name='star',
            unique_together=set([('userId', 'gameId')]),
        ),
        migrations.AlterUniqueTogether(
            name='gamereviewinfo',
            unique_together=set([('userId', 'gameId', 'date')]),
        ),
    ]
